In [1]:
import numpy as np
from numpy import array

action = {'ESC': 0, 'back': 0, 'drop': 0, 'forward': 0, 'hotbar.1': 0, 'hotbar.2': 0, 'hotbar.3': 0, 'hotbar.4': 0, 'hotbar.5': 0, 'hotbar.6': 0, 'hotbar.7': 0, 'hotbar.8': 0, 'hotbar.9': 0, 'inventory': 0, 'jump': 0, 'left': 0, 'right': 0, 'sneak': 0, 'sprint': 0, 'swapHands': 0, 'camera': array([1, 2]), 'attack': 1, 'use': 0, 'pickItem': 0}

action

{'ESC': 0,
 'back': 0,
 'drop': 0,
 'forward': 0,
 'hotbar.1': 0,
 'hotbar.2': 0,
 'hotbar.3': 0,
 'hotbar.4': 0,
 'hotbar.5': 0,
 'hotbar.6': 0,
 'hotbar.7': 0,
 'hotbar.8': 0,
 'hotbar.9': 0,
 'inventory': 0,
 'jump': 0,
 'left': 0,
 'right': 0,
 'sneak': 0,
 'sprint': 0,
 'swapHands': 0,
 'camera': array([1, 2]),
 'attack': 1,
 'use': 0,
 'pickItem': 0}

In [ ]:
import numpy as np

np.stack([acs.get(k, dummy) for k in Buttons.ALL], axis=-1),

In [17]:
import sys
sys.path.append("../")

from src.agent import MineRLAgent
import torch

import torch


in_model = "../data/VPT-models/2x.model"
in_weights = "../data/VPT-models/foundation-model-2x.weights"
out_weights = "../data/agent_st/foundation-model-tl-tt-2x.weights"

environment = "MineRLBasaltFindCave-v0"
device = "cuda"

from src.agent import ACTION_TRANSFORMER_KWARGS
import pickle
from src.lib.actions import ActionTransformer
from gym3.types import DictType, Discrete, TensorType
from src.lib.action_mapping import CameraHierarchicalMapping

agent_parameters = pickle.load(open(in_model, "rb"))
policy_kwargs = agent_parameters["model"]["args"]["net"]["args"]
pi_head_kwargs = agent_parameters["model"]["args"]["pi_head_opts"]
pi_head_kwargs["temperature"] = float(pi_head_kwargs["temperature"])

device = torch.device("cuda")
action_mapper = CameraHierarchicalMapping(n_camera_bins=11)
action_space = action_mapper.get_action_space_update()
action_space = DictType(**action_space)

action_transformer = ActionTransformer(**ACTION_TRANSFORMER_KWARGS)

agent_kwargs = dict(policy_kwargs=policy_kwargs, pi_head_kwargs=pi_head_kwargs, action_space=action_space)


agent = MineRLAgent(
    None,
    device=torch.device("cuda"),
    policy_kwargs=policy_kwargs,
    pi_head_kwargs=pi_head_kwargs,
)
agent.load_weights(in_weights)


policy_kwargs={'active_reward_monitors': {'craft_stats': {'args': {'collapse_var': True, 'items': ['planks', 'stick', 'crafting_table', 'wooden_pickaxe', 'stone_pickaxe', 'furnace', 'iron_ingot', 'iron_pickaxe', 'diamond_pickaxe', 'torch']}, 'weight': 0}, 'mine_stats': {'args': {'collapse_var': True, 'items': ['log', 'coal_ore', 'stone', 'iron_ore', 'diamond_ore', 'obsidian']}, 'weight': 0}, 'order_invariant_curriculum': {'args': {'curriculum': {'coal': [5, 0.4], 'cobblestone': [11, 0.09090909090909091], 'crafting_table': [1, 1], 'diamond': [10000, 2.6666666666666665], 'diamond_pickaxe': [10000, 8], 'furnace': [1, 1], 'iron_ingot': [3, 1.3333333333333333], 'iron_ore': [3, 1.3333333333333333], 'iron_pickaxe': [1, 4], 'log': [8, 0.125], 'obsidian': [10000, 16], 'planks': [20, 0.05], 'stick': [16, 0.0625], 'stone_pickaxe': [1, 1], 'torch': [16, 0.125], 'wooden_pickaxe': [1, 1]}}, 'weight': 1}, 'pickup_stats': {'args': {'collapse_var': True, 'items': ['log', 'coal', 'cobblestone', 'iron_or

In [25]:
batch = np.concatenate((np.array(action)[None], np.array(action)[None]), axis=0)

In [24]:
action

{'ESC': 0,
 'back': 0,
 'drop': 0,
 'forward': 0,
 'hotbar.1': 0,
 'hotbar.2': 0,
 'hotbar.3': 0,
 'hotbar.4': 0,
 'hotbar.5': 0,
 'hotbar.6': 0,
 'hotbar.7': 0,
 'hotbar.8': 0,
 'hotbar.9': 0,
 'inventory': 0,
 'jump': 0,
 'left': 0,
 'right': 0,
 'sneak': 0,
 'sprint': 0,
 'swapHands': 0,
 'camera': array([1, 2]),
 'attack': 1,
 'use': 0,
 'pickItem': 0}

In [26]:
agent_action = agent._env_action_to_agent(
    action, to_torch=True, check_if_null=True
)
agent_action

{'buttons': tensor([[5]], device='cuda:0'),
 'camera': tensor([[73]], device='cuda:0')}

In [27]:
agent_action = agent._env_action_to_agent(
    batch, to_torch=True, check_if_null=True
)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [29]:
batch

array([{'ESC': 0, 'back': 0, 'drop': 0, 'forward': 0, 'hotbar.1': 0, 'hotbar.2': 0, 'hotbar.3': 0, 'hotbar.4': 0, 'hotbar.5': 0, 'hotbar.6': 0, 'hotbar.7': 0, 'hotbar.8': 0, 'hotbar.9': 0, 'inventory': 0, 'jump': 0, 'left': 0, 'right': 0, 'sneak': 0, 'sprint': 0, 'swapHands': 0, 'camera': array([1, 2]), 'attack': 1, 'use': 0, 'pickItem': 0},
       {'ESC': 0, 'back': 0, 'drop': 0, 'forward': 0, 'hotbar.1': 0, 'hotbar.2': 0, 'hotbar.3': 0, 'hotbar.4': 0, 'hotbar.5': 0, 'hotbar.6': 0, 'hotbar.7': 0, 'hotbar.8': 0, 'hotbar.9': 0, 'inventory': 0, 'jump': 0, 'left': 0, 'right': 0, 'sneak': 0, 'sprint': 0, 'swapHands': 0, 'camera': array([1, 2]), 'attack': 1, 'use': 0, 'pickItem': 0}],
      dtype=object)

In [1]:
import torch
from torch import nn

# an Embedding module containing 10 tensors of size 3
embedding = nn.Embedding(10, 3)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])
embedding(input)



# example with padding_idx
embedding = nn.Embedding(10, 3, padding_idx=0)
input = torch.LongTensor([[0,2,0,5]])
embedding(input)

# example of changing `pad` vector
padding_idx = 0
embedding = nn.Embedding(3, 3, padding_idx=padding_idx)
embedding.weight
with torch.no_grad():
    embedding.weight[padding_idx] = torch.ones(3)
embedding.weight

Parameter containing:
tensor([[ 1.0000,  1.0000,  1.0000],
        [-0.2813, -0.6042,  1.3380],
        [-1.3182, -1.5247,  0.7908]], requires_grad=True)

In [10]:
import torch
from torch import nn

embedding = nn.Embedding(10, 3)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
embedding(input)


tensor([[-0.1791, -1.4786, -0.1154],
        [ 1.2455,  1.0634, -0.8497],
        [-1.5669,  0.4748,  0.9578],
        [ 0.7715, -1.1459, -1.1600],
        [ 0.2507, -0.7769, -0.4420],
        [-1.2183,  1.5122, -0.0402],
        [-0.1726,  0.2697, -1.6306],
        [ 0.3161, -0.1922, -2.1125],
        [-0.8778, -0.7724, -0.8507],
        [ 1.7138,  0.3540,  1.0472]], grad_fn=<EmbeddingBackward0>)

In [6]:
embedding.weight

Parameter containing:
tensor([[ 0.2511, -0.1162,  0.1950],
        [-0.6969,  0.3637,  0.6909],
        [ 0.1259,  1.0499, -3.4100],
        [-0.4170, -0.0376, -0.7726],
        [-1.1543, -1.4417,  0.8481],
        [ 0.1249, -0.2237,  2.0584],
        [ 2.3056,  0.8252,  0.5547],
        [-1.1525, -1.4594, -1.0760],
        [-0.1649, -0.3159, -0.5948],
        [-0.8411,  0.7088,  0.4963]], requires_grad=True)

In [16]:
from torch import nn
import torch

n_workers = 4
# Define the nn.Embedding layer
emb = nn.Embedding(n_workers, 5)
emb.requires_grad_(False)

emb.weight[torch.LongTensor([0, 2])] = torch.zeros((2, 5))

In [17]:
emb(torch.LongTensor([0, 2]))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
emb.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.7215,  0.4973, -0.3135, -0.3438, -0.1302],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.2719, -0.1331,  1.0734, -0.2849,  0.1590]])